name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          key: ${{secrets.SERVER_SSH_SK}}
          port: ${{secrets.SERVER_PORT}}
          script: |
            cd Ataraxia
            git fetch --all
            git reset --hard origin/master
            git status
            npm install
            npm run build
